import {
  Bell,
  Coin,
  DataAnalysis,
  Files,
  House,
  Key,
  OfficeBuilding,
  Platform,
  Setting,
  Tickets,
  Tools,
  TrendCharts,
  User,
  Van,
} from '@element-plus/icons-vue'

export interface FieldConfig {
  prop: string
  label: string
  type?:
    | 'text'
    | 'number'
    | 'date'
    | 'datetime'
    | 'textarea'
    | 'select'
    | 'province'
    | 'city'
    | 'district'
    | 'project'
    | 'building'
    | 'unit'
    | 'house'
    | 'parkingArea'
    | 'parkingSpace'
    | 'plateNo'
    | 'feeItem'
    | 'feeStandard'
    | 'billObject'
    | 'billObjectMulti'
    | 'vehicleBrandId'
    | 'vehicleBrand'
    | 'vehicleModel'
  options?: Array<string | { label: string; value: string | number | boolean }>
  required?: boolean
  inFilter?: boolean
  tableHidden?: boolean
}

export interface PageConfig {
  key: string
  title: string
  group: string
  route: string
  icon?: unknown
  listPath: string
  createPath?: string
  updatePath?: string
  idProp?: string
  permission: string
  createPermission?: string
  updatePermission?: string
  projectScoped?: boolean
  menuOrder?: number
  showDetails?: boolean
  columns: FieldConfig[]
  detailFields?: FieldConfig[]
  fields?: FieldConfig[]
}

const enabledStatusOptions = [{ label: '启用', value: 'ACTIVE' }, { label: '停用', value: 'DISABLED' }]
const memberStatusOptions = enabledStatusOptions
const memberBindRoleOptions = [
  { label: '业主', value: 'OWNER' },
  { label: '家属', value: 'FAMILY' },
  { label: '租户', value: 'TENANT' },
  { label: '住户', value: 'RESIDENT' },
]
const memberBindingStatusOptions = [
  { label: '待审核', value: 'PENDING' },
  { label: '已通过', value: 'APPROVED' },
  { label: '已驳回', value: 'REJECTED' },
  { label: '已解绑', value: 'UNBOUND' },
]
const memberBindingSourceOptions = [
  { label: '业主端提交', value: '业主端提交' },
  { label: '物业端提交', value: '物业端提交' },
  { label: '业主邀请', value: '业主邀请' },
]
const memberRelationshipOptions = [
  { label: '配偶', value: 'SPOUSE' },
  { label: '父母', value: 'PARENT' },
  { label: '子女', value: 'CHILD' },
  { label: '亲属', value: 'RELATIVE' },
  { label: '租户', value: 'TENANT' },
  { label: '其他', value: 'OTHER' },
]
const yesNoOptions = [
  { label: '是', value: true },
  { label: '否', value: false },
]
const projectTypeOptions = [
  { label: '住宅小区', value: 'RESIDENTIAL' },
  { label: '商业项目', value: 'COMMERCIAL' },
  { label: '园区', value: 'PARK' },
  { label: '综合业态', value: 'MIXED' },
]
const houseUsageOptions = [
  { label: '住宅', value: 'RESIDENTIAL' },
  { label: '商业', value: 'COMMERCIAL' },
  { label: '办公', value: 'OFFICE' },
  { label: '车位/车库', value: 'PARKING' },
]
const houseStatusOptions = [
  { label: '空置', value: 'VACANT' },
  { label: '已入住', value: 'OCCUPIED' },
  { label: '已出租', value: 'RENTED' },
  { label: '装修中', value: 'RENOVATING' },
  { label: '已锁定', value: 'LOCKED' },
]
const parkingSpaceTypeOptions = [
  { label: '地面车位', value: 'GROUND' },
  { label: '地下车位', value: 'UNDERGROUND' },
  { label: '机械车位', value: 'MECHANICAL' },
]
const parkingSpaceStatusOptions = [
  { label: '空闲', value: 'AVAILABLE' },
  { label: '已占用', value: 'OCCUPIED' },
  { label: '锁定', value: 'LOCKED' },
  { label: '停用', value: 'DISABLED' },
]
const vehicleTypeOptions = [
  { label: '燃油车', value: 'CAR' },
  { label: '新能源车', value: 'EV' },
  { label: '摩托车', value: 'MOTORCYCLE' },
]
const vehicleSpaceStatusOptions = [
  { label: '未关联车位', value: 'NONE' },
  { label: '月租', value: 'ACTIVE' },
  { label: '已购买', value: 'SOLD' },
  { label: '月租到期', value: 'EXPIRED' },
  { label: '暂停', value: 'SUSPENDED' },
]
const feeItemTypeOptions = [
  { label: '周期性收费', value: 'PERIODIC' },
  { label: '一次性收费', value: 'ONCE' },
  { label: '押金', value: 'DEPOSIT' },
  { label: '预存款', value: 'PREPAID' },
  { label: '代收费用', value: 'AGENCY' },
]
const chargeMethodOptions = [
  { label: '固定金额', value: 'FIXED' },
  { label: '按建筑面积', value: 'AREA' },
  { label: '按用量', value: 'METER' },
  { label: '自定义公式', value: 'FORMULA' },
]
const billingCycleOptions = [
  { label: '月', value: 'MONTH' },
  { label: '季度', value: 'QUARTER' },
  { label: '年', value: 'YEAR' },
  { label: '一次性', value: 'ONCE' },
]
const billObjectTypeOptions = [
  { label: '房屋', value: 'HOUSE' },
  { label: '车辆', value: 'VEHICLE' },
  { label: '车位', value: 'SPACE' },
  { label: '合同', value: 'CONTRACT' },
]
const billStatusOptions = [
  { label: '未缴', value: 'UNPAID' },
  { label: '支付中', value: 'PAYING' },
  { label: '部分已缴', value: 'PARTIAL_PAID' },
  { label: '已缴清', value: 'PAID' },
  { label: '逾期', value: 'OVERDUE' },
  { label: '已作废', value: 'VOID' },
  { label: '已退款', value: 'REFUNDED' },
  { label: '部分退款', value: 'PARTIAL_REFUNDED' },
]
const payChannelOptions = [
  { label: '微信支付', value: 'WECHAT' },
  { label: '支付宝', value: 'ALI' },
  { label: '现金', value: 'CASH' },
  { label: 'POS刷卡', value: 'POS' },
  { label: '银行转账', value: 'BANK_TRANSFER' },
  { label: '线下收款', value: 'OFFLINE' },
]
const payOrderStatusOptions = [
  { label: '待支付', value: 'PENDING' },
  { label: '支付中', value: 'PAYING' },
  { label: '已支付', value: 'PAID' },
  { label: '已关闭', value: 'CLOSED' },
  { label: '退款中', value: 'REFUNDING' },
  { label: '已退款', value: 'REFUNDED' },
  { label: '部分退款', value: 'PARTIAL_REFUNDED' },
]
const refundStatusOptions = [
  { label: '待审核', value: 'APPLYING' },
  { label: '退款中', value: 'REFUNDING' },
  { label: '已退款', value: 'REFUNDED' },
  { label: '已拒绝', value: 'AUDIT_REJECTED' },
  { label: '退款失败', value: 'FAILED' },
  { label: '已关闭', value: 'CLOSED' },
]
const prepaymentSourceOptions = [
  { label: '超额收款', value: 'OFFLINE_OVERPAY' },
]
const reconcileExceptionStatusOptions = [
  { label: '未处理', value: 'OPEN' },
  { label: '已处理', value: 'HANDLED' },
]
const reconcileExceptionTypeOptions = [
  { label: '订单缺少支付流水', value: '订单缺少支付流水' },
  { label: '支付流水订单异常', value: '支付流水订单异常' },
  { label: '退款缺少退款流水', value: '退款缺少退款流水' },
  { label: '订单金额不一致', value: '订单金额不一致' },
  { label: '账单金额状态异常', value: '账单金额状态异常' },
]

export const pages: PageConfig[] = [
  {
    key: 'platform-tenants',
    title: '租户管理',
    group: '平台运营',
    route: '/platform/tenants',
    icon: Platform,
    listPath: '/platform/tenants',
    createPath: '/platform/tenants',
    updatePath: '/platform/tenants/:tenantId',
    idProp: 'tenantId',
    permission: 'platform:tenant:list',
    createPermission: 'platform:tenant:create',
    updatePermission: 'platform:tenant:update',
    columns: [
      { prop: 'tenantName', label: '租户名称', inFilter: true },
      { prop: 'tenantCode', label: '编码' },
      { prop: 'contactName', label: '联系人' },
      { prop: 'contactMobile', label: '手机号' },
      { prop: 'status', label: '状态', inFilter: true },
      { prop: 'serviceEndDate', label: '服务到期' },
    ],
    fields: [
      { prop: 'tenantName', label: '租户名称', required: true },
      { prop: 'tenantCode', label: '租户编码', required: true },
      { prop: 'contactName', label: '联系人', required: true },
      { prop: 'contactMobile', label: '联系电话', required: true },
      { prop: 'packageId', label: '套餐ID', type: 'number', required: true },
      { prop: 'serviceStartDate', label: '开始日期', type: 'date' },
      { prop: 'serviceEndDate', label: '结束日期', type: 'date' },
      { prop: 'remark', label: '备注', type: 'textarea' },
    ],
  },
  {
    key: 'platform-packages',
    title: '租户套餐',
    group: '平台运营',
    route: '/platform/packages',
    icon: Tickets,
    listPath: '/platform/packages',
    createPath: '/platform/packages',
    idProp: 'packageId',
    permission: 'platform:package:list',
    createPermission: 'platform:package:create',
    columns: [
      { prop: 'packageName', label: '套餐名称', inFilter: true },
      { prop: 'packageCode', label: '编码' },
      { prop: 'price', label: '价格' },
      { prop: 'billingCycle', label: '周期' },
      { prop: 'status', label: '状态' },
    ],
    fields: [
      { prop: 'packageName', label: '套餐名称', required: true },
      { prop: 'packageCode', label: '套餐编码', required: true },
      { prop: 'price', label: '价格', type: 'number', required: true },
      { prop: 'billingCycle', label: '计费周期', type: 'select', options: ['MONTH', 'YEAR'], required: true },
      { prop: 'enabledModules', label: '模块JSON', type: 'textarea' },
      { prop: 'quotas', label: '额度JSON', type: 'textarea' },
      { prop: 'status', label: '状态', type: 'select', options: ['ACTIVE', 'DISABLED'] },
    ],
  },
  {
    key: 'projects',
    title: '小区名称',
    group: '基础档案',
    route: '/base/projects',
    icon: OfficeBuilding,
    listPath: '/base/projects',
    createPath: '/base/projects',
    updatePath: '/base/projects/:projectId',
    idProp: 'projectId',
    permission: 'base:project:list',
    createPermission: 'base:project:create',
    updatePermission: 'base:project:update',
    menuOrder: 10,
    showDetails: true,
    columns: [
      { prop: 'projectName', label: '小区名称', inFilter: true },
      { prop: 'projectCode', label: '小区编码' },
      { prop: 'city', label: '城市' },
      { prop: 'address', label: '地址' },
      { prop: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
    ],
    fields: [
      { prop: 'projectName', label: '小区名称', required: true },
      { prop: 'projectType', label: '项目类型', type: 'select', options: projectTypeOptions },
      { prop: 'province', label: '省份', type: 'province' },
      { prop: 'city', label: '城市', type: 'city' },
      { prop: 'district', label: '区县', type: 'district' },
      { prop: 'address', label: '地址' },
      { prop: 'servicePhone', label: '服务电话' },
      { prop: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
    ],
    detailFields: [
      { prop: 'projectName', label: '小区名称' },
      { prop: 'projectCode', label: '小区编码' },
      { prop: 'projectType', label: '项目类型', type: 'select', options: projectTypeOptions },
      { prop: 'province', label: '省份' },
      { prop: 'city', label: '城市' },
      { prop: 'district', label: '区县' },
      { prop: 'address', label: '地址' },
      { prop: 'servicePhone', label: '服务电话' },
      { prop: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
    ],
  },
  {
    key: 'houses',
    title: '房屋管理',
    group: '基础档案',
    route: '/base/houses',
    icon: House,
    listPath: '/base/houses',
    createPath: '/base/houses',
    updatePath: '/base/houses/:houseId',
    idProp: 'houseId',
    permission: 'base:house:list',
    createPermission: 'base:house:create',
    updatePermission: 'base:house:update',
    projectScoped: true,
    menuOrder: 45,
    columns: [
      { prop: 'projectId', label: '小区名称', type: 'project' },
      { prop: 'buildingId', label: '楼栋名称', type: 'building' },
      { prop: 'unitId', label: '单元', type: 'unit' },
      { prop: 'houseNo', label: '房屋', inFilter: true },
      { prop: 'buildingArea', label: '面积' },
      { prop: 'houseStatus', label: '状态', type: 'select', options: houseStatusOptions },
    ],
    fields: [
      { prop: 'projectId', label: '小区名称', type: 'project', required: true },
      { prop: 'buildingId', label: '楼栋名称', type: 'building', required: true },
      { prop: 'unitId', label: '单元', type: 'unit', required: true },
      { prop: 'houseNo', label: '房屋', required: true },
      { prop: 'floorNo', label: '楼层', type: 'number' },
      { prop: 'buildingArea', label: '建筑面积', type: 'number' },
      { prop: 'houseUsage', label: '用途', type: 'select', options: houseUsageOptions },
      { prop: 'houseStatus', label: '状态', type: 'select', options: houseStatusOptions },
    ],
  },
  {
    key: 'members',
    title: '业主/住户',
    group: '基础档案',
    route: '/base/members',
    icon: User,
    listPath: '/base/members',
    createPath: '/base/members',
    updatePath: '/base/members/:memberId',
    idProp: 'memberId',
    permission: 'base:member:list',
    createPermission: 'base:member:create',
    updatePermission: 'base:member:update',
    menuOrder: 50,
    columns: [
      { prop: 'realName', label: '业主/住户', inFilter: true },
      { prop: 'mobile', label: '手机号' },
      { prop: 'bindRole', label: '住户类型', type: 'select', options: memberBindRoleOptions },
      { prop: 'status', label: '状态', type: 'select', options: memberStatusOptions },
      { prop: 'projectId', label: '小区名称', type: 'project' },
      { prop: 'buildingId', label: '楼栋名称', type: 'building' },
      { prop: 'unitId', label: '单元', type: 'unit' },
      { prop: 'houseId', label: '房屋', type: 'house' },
      { prop: 'createdAt', label: '创建时间' },
    ],
    fields: [
      { prop: 'projectId', label: '小区名称', type: 'project', required: true },
      { prop: 'buildingId', label: '楼栋名称', type: 'building', required: true },
      { prop: 'unitId', label: '单元', type: 'unit', required: true },
      { prop: 'houseId', label: '房屋', type: 'house', required: true },
      { prop: 'realName', label: '业主/住户', required: true },
      { prop: 'mobile', label: '手机号', required: true },
      { prop: 'bindRole', label: '住户类型', type: 'select', options: memberBindRoleOptions },
      { prop: 'openid', label: '微信 openid' },
      { prop: 'unionid', label: '微信 unionid' },
      { prop: 'avatarUrl', label: '头像地址' },
      { prop: 'status', label: '状态', type: 'select', options: memberStatusOptions },
    ],
  },
  {
    key: 'vehicles',
    title: '车辆管理',
    group: '基础档案',
    route: '/base/vehicles',
    icon: Van,
    listPath: '/base/vehicles',
    createPath: '/base/vehicles',
    updatePath: '/base/vehicles/:vehicleId',
    idProp: 'vehicleId',
    permission: 'base:vehicle:list',
    createPermission: 'base:vehicle:create',
    updatePermission: 'base:vehicle:update',
    projectScoped: true,
    menuOrder: 70,
    columns: [
      { prop: 'memberName', label: '业主/住户' },
      { prop: 'memberMobile', label: '手机号' },
      { prop: 'projectId', label: '小区名称', type: 'project' },
      { prop: 'buildingId', label: '楼栋名称', type: 'building' },
      { prop: 'unitId', label: '单元', type: 'unit' },
      { prop: 'houseId', label: '房屋', type: 'house' },
      { prop: 'plateNo', label: '车牌号', inFilter: true },
      { prop: 'vehicleBrand', label: '品牌' },
      { prop: 'vehicleModel', label: '型号' },
      { prop: 'spaceId', label: '车位', type: 'parkingSpace' },
      { prop: 'monthlyRentStatus', label: '车位租售状态', type: 'select', options: vehicleSpaceStatusOptions },
      { prop: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
    ],
    fields: [
      { prop: 'projectId', label: '小区名称', type: 'project', required: true },
      { prop: 'plateNo', label: '车牌号', type: 'plateNo', required: true },
      { prop: 'vehicleType', label: '车辆类型', type: 'select', options: vehicleTypeOptions },
      { prop: 'vehicleBrand', label: '车辆品牌', type: 'vehicleBrand' },
      { prop: 'vehicleModel', label: '车辆型号', type: 'vehicleModel' },
      { prop: 'memberId', label: '会员ID', type: 'number' },
      { prop: 'houseId', label: '房屋ID', type: 'number' },
      { prop: 'spaceId', label: '车位', type: 'parkingSpace' },
      { prop: 'monthlyRentStatus', label: '车位租售状态', type: 'select', options: vehicleSpaceStatusOptions },
      { prop: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
    ],
  },
]

const baseArchiveExtraPages: PageConfig[] = [
  {
    key: 'vehicle-brands',
    title: '车辆品牌',
    group: '基础档案',
    route: '/base/vehicle-brands',
    icon: Van,
    listPath: '/base/vehicle-brands',
    createPath: '/base/vehicle-brands',
    updatePath: '/base/vehicle-brands/:brandId',
    idProp: 'brandId',
    permission: 'base:vehicle:list',
    createPermission: 'base:vehicle:update',
    updatePermission: 'base:vehicle:update',
    menuOrder: 72,
    columns: [
      { prop: 'brandName', label: '品牌名称', inFilter: true },
      { prop: 'brandCode', label: '品牌编码' },
      { prop: 'sortNo', label: '排序' },
      { prop: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
    ],
    fields: [
      { prop: 'brandName', label: '品牌名称', required: true },
      { prop: 'brandCode', label: '品牌编码' },
      { prop: 'sortNo', label: '排序', type: 'number' },
      { prop: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
    ],
  },
  {
    key: 'vehicle-models',
    title: '车辆型号',
    group: '基础档案',
    route: '/base/vehicle-models',
    icon: Van,
    listPath: '/base/vehicle-models',
    createPath: '/base/vehicle-models',
    updatePath: '/base/vehicle-models/:modelId',
    idProp: 'modelId',
    permission: 'base:vehicle:list',
    createPermission: 'base:vehicle:update',
    updatePermission: 'base:vehicle:update',
    menuOrder: 74,
    columns: [
      { prop: 'brandId', label: '品牌名称', type: 'vehicleBrandId' },
      { prop: 'modelName', label: '型号名称', inFilter: true },
      { prop: 'sortNo', label: '排序' },
      { prop: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
    ],
    fields: [
      { prop: 'brandId', label: '品牌名称', type: 'vehicleBrandId', required: true },
      { prop: 'modelName', label: '型号名称', required: true },
      { prop: 'sortNo', label: '排序', type: 'number' },
      { prop: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
    ],
  },
  {
    key: 'buildings',
    title: '楼栋管理',
    group: '基础档案',
    route: '/base/buildings',
    icon: OfficeBuilding,
    listPath: '/base/buildings',
    createPath: '/base/buildings',
    updatePath: '/base/buildings/:buildingId',
    idProp: 'buildingId',
    permission: 'base:building:list',
    createPermission: 'base:building:create',
    updatePermission: 'base:building:update',
    projectScoped: true,
    menuOrder: 30,
    columns: [
      { prop: 'projectId', label: '小区名称', type: 'project' },
      { prop: 'buildingName', label: '楼栋名称', inFilter: true },
      { prop: 'floorCount', label: '层数' },
      { prop: 'status', label: '状态', type: 'select', options: enabledStatusOptions, inFilter: true },
    ],
    fields: [
      { prop: 'projectId', label: '小区名称', type: 'project', required: true },
      { prop: 'buildingName', label: '楼栋名称', required: true },
      { prop: 'floorCount', label: '层数', type: 'number' },
      { prop: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
    ],
  },
  {
    key: 'units',
    title: '单元管理',
    group: '基础档案',
    route: '/base/units',
    icon: House,
    listPath: '/base/units',
    createPath: '/base/units',
    updatePath: '/base/units/:unitId',
    idProp: 'unitId',
    permission: 'base:unit:list',
    createPermission: 'base:unit:create',
    updatePermission: 'base:unit:update',
    projectScoped: true,
    menuOrder: 40,
    columns: [
      { prop: 'projectId', label: '小区名称', type: 'project' },
      { prop: 'buildingId', label: '楼栋名称', type: 'building' },
      { prop: 'unitName', label: '单元', inFilter: true },
      { prop: 'status', label: '状态', type: 'select', options: enabledStatusOptions, inFilter: true },
    ],
    fields: [
      { prop: 'projectId', label: '小区名称', type: 'project', required: true },
      { prop: 'buildingId', label: '楼栋名称', type: 'building', required: true },
      { prop: 'unitName', label: '单元名称', required: true },
      { prop: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
    ],
  },
  {
    key: 'member-bindings',
    title: '房屋绑定审核',
    group: '基础档案',
    route: '/base/member-bindings',
    icon: User,
    listPath: '/base/member-bindings',
    permission: 'base:memberBinding:list',
    projectScoped: true,
    menuOrder: 80,
    showDetails: true,
    columns: [
      { prop: 'projectId', label: '小区名称', type: 'project' },
      { prop: 'buildingName', label: '楼栋名称' },
      { prop: 'unitName', label: '单元' },
      { prop: 'houseNo', label: '房屋' },
      { prop: 'realName', label: '业主/住户', inFilter: true },
      { prop: 'mobile', label: '手机号' },
      { prop: 'applySource', label: '申请来源', type: 'select', options: memberBindingSourceOptions },
      { prop: 'status', label: '审核状态', type: 'select', options: memberBindingStatusOptions, inFilter: true },
      { prop: 'bindRole', label: '住户类型', type: 'select', options: memberBindRoleOptions },
      { prop: 'relationship', label: '关系', type: 'select', options: memberRelationshipOptions },
      { prop: 'createdAt', label: '申请时间' },
    ],
    detailFields: [
      { prop: 'projectId', label: '小区名称', type: 'project' },
      { prop: 'buildingName', label: '楼栋名称' },
      { prop: 'unitName', label: '单元' },
      { prop: 'houseNo', label: '房屋' },
      { prop: 'realName', label: '业主/住户' },
      { prop: 'mobile', label: '手机号' },
      { prop: 'applySource', label: '申请来源' },
      { prop: 'status', label: '审核状态', type: 'select', options: memberBindingStatusOptions },
      { prop: 'bindRole', label: '住户类型', type: 'select', options: memberBindRoleOptions },
      { prop: 'relationship', label: '关系', type: 'select', options: memberRelationshipOptions },
      { prop: 'allowNotice', label: '允许通知', type: 'select', options: yesNoOptions },
      { prop: 'allowBill', label: '允许看账单', type: 'select', options: yesNoOptions },
      { prop: 'allowPayment', label: '允许缴费', type: 'select', options: yesNoOptions },
      { prop: 'allowWorkOrder', label: '允许报修', type: 'select', options: yesNoOptions },
      { prop: 'allowVisitor', label: '允许访客', type: 'select', options: yesNoOptions },
      { prop: 'auditRemark', label: '审核/驳回备注' },
      { prop: 'createdAt', label: '申请时间' },
      { prop: 'auditAt', label: '审核时间' },
    ],
  },
  {
    key: 'parking-areas',
    title: '车位区域',
    group: '基础档案',
    route: '/base/parking-areas',
    icon: Van,
    listPath: '/base/parking-areas',
    createPath: '/base/parking-areas',
    updatePath: '/base/parking-areas/:areaId',
    idProp: 'areaId',
    permission: 'base:parkingArea:list',
    createPermission: 'base:parkingArea:create',
    updatePermission: 'base:parkingArea:update',
    projectScoped: true,
    menuOrder: 55,
    columns: [
      { prop: 'projectId', label: '小区名称', type: 'project' },
      { prop: 'areaName', label: '区域', inFilter: true },
      { prop: 'status', label: '状态', type: 'select', options: enabledStatusOptions, inFilter: true },
    ],
    fields: [
      { prop: 'projectId', label: '小区名称', type: 'project', required: true },
      { prop: 'areaName', label: '区域', required: true },
      { prop: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
    ],
  },
  {
    key: 'parking-spaces',
    title: '车位管理',
    group: '基础档案',
    route: '/base/parking-spaces',
    icon: Van,
    listPath: '/base/parking-spaces',
    createPath: '/base/parking-spaces',
    updatePath: '/base/parking-spaces/:spaceId',
    idProp: 'spaceId',
    permission: 'base:parkingSpace:list',
    createPermission: 'base:parkingSpace:create',
    updatePermission: 'base:parkingSpace:update',
    projectScoped: true,
    menuOrder: 60,
    showDetails: true,
    columns: [
      { prop: 'projectId', label: '小区名称', type: 'project' },
      { prop: 'buildingId', label: '楼栋名称', type: 'building' },
      { prop: 'unitId', label: '单元', type: 'unit' },
      { prop: 'houseId', label: '房屋', type: 'house' },
      { prop: 'areaId', label: '区域', type: 'parkingArea' },
      { prop: 'spaceNo', label: '车位编号', inFilter: true },
      { prop: 'spaceType', label: '类型', type: 'select', options: parkingSpaceTypeOptions },
      { prop: 'boundPlateNo', label: '绑定车牌' },
      { prop: 'boundMemberName', label: '业主/住户' },
      { prop: 'boundMemberMobile', label: '手机号' },
      { prop: 'monthlyRentStatus', label: '车位租售状态', type: 'select', options: vehicleSpaceStatusOptions },
      { prop: 'status', label: '状态', type: 'select', options: parkingSpaceStatusOptions, inFilter: true },
    ],
    fields: [
      { prop: 'projectId', label: '小区名称', type: 'project', required: true },
      { prop: 'buildingId', label: '楼栋名称', type: 'building', required: true },
      { prop: 'unitId', label: '单元', type: 'unit', required: true },
      { prop: 'houseId', label: '房屋', type: 'house', required: true },
      { prop: 'areaId', label: '区域', type: 'parkingArea', required: true },
      { prop: 'spaceNo', label: '车位编号', required: true },
      { prop: 'spaceType', label: '类型', type: 'select', options: parkingSpaceTypeOptions },
      { prop: 'status', label: '状态', type: 'select', options: parkingSpaceStatusOptions },
    ],
    detailFields: [
      { prop: 'projectId', label: '小区名称', type: 'project' },
      { prop: 'buildingId', label: '楼栋名称', type: 'building' },
      { prop: 'unitId', label: '单元', type: 'unit' },
      { prop: 'houseId', label: '房屋', type: 'house' },
      { prop: 'areaId', label: '区域', type: 'parkingArea' },
      { prop: 'spaceNo', label: '车位编号' },
      { prop: 'spaceType', label: '类型', type: 'select', options: parkingSpaceTypeOptions },
      { prop: 'status', label: '车位状态', type: 'select', options: parkingSpaceStatusOptions },
      { prop: 'boundPlateNo', label: '绑定车牌' },
      { prop: 'boundVehicleBrand', label: '车辆品牌' },
      { prop: 'boundVehicleModel', label: '车辆型号' },
      { prop: 'boundMemberName', label: '业主/住户' },
      { prop: 'boundMemberMobile', label: '手机号' },
      { prop: 'monthlyRentStatus', label: '车位租售状态', type: 'select', options: vehicleSpaceStatusOptions },
    ],
  },
]

const platformExtraPages: PageConfig[] = [
  {
    key: 'platform-notices',
    title: '平台公告',
    group: '平台运营',
    route: '/platform/notices',
    icon: Bell,
    listPath: '/platform/notices',
    createPath: '/platform/notices',
    idProp: 'noticeId',
    permission: 'platform:notice:list',
    createPermission: 'platform:notice:create',
    columns: [
      { prop: 'title', label: '标题', inFilter: true },
      { prop: 'noticeType', label: '类型' },
      { prop: 'targetScope', label: '范围' },
      { prop: 'publishStatus', label: '状态' },
      { prop: 'publishedAt', label: '发布时间' },
    ],
    fields: [
      { prop: 'title', label: '标题', required: true },
      { prop: 'content', label: '内容', type: 'textarea', required: true },
      { prop: 'noticeType', label: '类型', type: 'select', options: ['PROPERTY', 'SYSTEM', 'ACTIVITY', 'BILL'] },
      { prop: 'targetScope', label: '范围', type: 'select', options: ['TENANT', 'PROJECT', 'MEMBER', 'HOUSE'] },
    ],
  },
  {
    key: 'platform-usage',
    title: '用量统计',
    group: '平台运营',
    route: '/platform/usage',
    icon: DataAnalysis,
    listPath: '/platform/usage',
    permission: 'platform:usage:view',
    columns: [
      { prop: 'tenantName', label: '租户名称', inFilter: true },
      { prop: 'projectCount', label: '项目数' },
      { prop: 'userCount', label: '用户数' },
      { prop: 'storageUsedMb', label: '存储MB' },
      { prop: 'apiCallCount', label: '接口调用' },
    ],
  },
  {
    key: 'platform-audit',
    title: '操作审计',
    group: '平台运营',
    route: '/platform/audit',
    icon: Files,
    listPath: '/system/operation-logs',
    permission: 'system:operationLog:list',
    columns: [
      { prop: 'tenantId', label: '租户ID', inFilter: true },
      { prop: 'projectId', label: '项目ID', inFilter: true },
      { prop: 'operatorType', label: '操作者类型' },
      { prop: 'operatorId', label: '操作者ID' },
      { prop: 'moduleCode', label: '模块', inFilter: true },
      { prop: 'actionCode', label: '动作', inFilter: true },
      { prop: 'objectType', label: '对象类型', inFilter: true },
      { prop: 'objectId', label: '对象ID', inFilter: true },
      { prop: 'reason', label: '原因' },
      { prop: 'createdAt', label: '时间' },
    ],
  },
]

const billingPages: PageConfig[] = [
  {
    key: 'fee-items',
    title: '收费项目',
    group: '收费账务',
    route: '/fee/items',
    icon: Coin,
    listPath: '/fee/items',
    createPath: '/fee/items',
    updatePath: '/fee/items/:itemId',
    idProp: 'itemId',
    permission: 'fee:item:list',
    createPermission: 'fee:item:create',
    updatePermission: 'fee:item:update',
    columns: [
      { prop: 'itemCode', label: '编码', inFilter: true },
      { prop: 'itemName', label: '收费项目' },
      { prop: 'itemType', label: '类型', type: 'select', options: feeItemTypeOptions },
      { prop: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
    ],
    fields: [
      { prop: 'itemName', label: '收费项目', required: true },
      { prop: 'itemType', label: '类型', type: 'select', options: feeItemTypeOptions },
      { prop: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
    ],
  },
  {
    key: 'bills',
    title: '账单管理',
    group: '收费账务',
    route: '/fee/bills',
    icon: Files,
    listPath: '/fee/bills',
    idProp: 'billId',
    permission: 'fee:bill:list',
    projectScoped: true,
    columns: [
      { prop: 'billNo', label: '账单号', inFilter: true },
      { prop: 'projectId', label: '小区名称', type: 'project' },
      { prop: 'memberName', label: '业主/住户' },
      { prop: 'memberMobile', label: '手机号' },
      { prop: 'houseNo', label: '房号' },
      { prop: 'billPeriod', label: '账期' },
      { prop: 'detailSummary', label: '应收明细' },
      { prop: 'receivableAmount', label: '应收' },
      { prop: 'prepaymentAppliedAmount', label: '预存抵扣' },
      { prop: 'paidAmount', label: '已收' },
      { prop: 'remainingAmount', label: '待收' },
      { prop: 'dueDate', label: '到期日' },
      { prop: 'status', label: '状态', type: 'select', options: billStatusOptions, inFilter: true },
    ],
  },
  {
    key: 'payment-orders',
    title: '收款订单',
    group: '收费账务',
    route: '/payment/orders',
    icon: Tickets,
    listPath: '/payment/orders',
    permission: 'payment:order:list',
    projectScoped: true,
    showDetails: true,
    columns: [
      { prop: 'orderNo', label: '订单号', inFilter: true },
      { prop: 'projectId', label: '小区名称', type: 'project' },
      { prop: 'memberName', label: '业主/住户', inFilter: true },
      { prop: 'memberMobile', label: '手机号' },
      { prop: 'houseNo', label: '房号' },
      { prop: 'billSummary', label: '应收明细' },
      { prop: 'amount', label: '订单金额' },
      { prop: 'transactionAmount', label: '实收金额' },
      { prop: 'refundedAmount', label: '已退金额' },
      { prop: 'refundableAmount', label: '可退金额' },
      { prop: 'payChannel', label: '支付方式', type: 'select', options: payChannelOptions, inFilter: true },
      { prop: 'prepaymentAmount', label: '转预存款' },
      { prop: 'status', label: '状态', type: 'select', options: payOrderStatusOptions, inFilter: true },
      { prop: 'paidAt', label: '支付时间' },
    ],
    detailFields: [
      { prop: 'orderNo', label: '订单号' },
      { prop: 'projectId', label: '小区名称', type: 'project' },
      { prop: 'memberName', label: '业主/住户' },
      { prop: 'memberMobile', label: '手机号' },
      { prop: 'houseNo', label: '房号' },
      { prop: 'memberId', label: '会员ID' },
      { prop: 'billSummary', label: '应收明细' },
      { prop: 'subject', label: '摘要' },
      { prop: 'payChannel', label: '支付方式', type: 'select', options: payChannelOptions },
      { prop: 'amount', label: '订单金额' },
      { prop: 'transactionAmount', label: '实收金额' },
      { prop: 'refundedAmount', label: '已退金额' },
      { prop: 'refundableAmount', label: '可退金额' },
      { prop: 'billCount', label: '核销账单数' },
      { prop: 'billAppliedAmount', label: '核销账单金额' },
      { prop: 'prepaymentAmount', label: '转入预存款' },
      { prop: 'prepaymentRemainingAmount', label: '预存款剩余' },
      { prop: 'subject', label: '摘要' },
      { prop: 'status', label: '状态', type: 'select', options: payOrderStatusOptions },
      { prop: 'expireAt', label: '过期时间' },
      { prop: 'paidAt', label: '支付时间' },
      { prop: 'thirdTradeNo', label: '第三方流水号' },
      { prop: 'createdAt', label: '创建时间' },
    ],
  },
  {
    key: 'refunds',
    title: '退款管理',
    group: '收费账务',
    route: '/payment/refunds',
    icon: TrendCharts,
    listPath: '/payment/refunds',
    createPath: '/payment/refunds',
    idProp: 'refundId',
    permission: 'payment:refund:list',
    createPermission: 'payment:refund:create',
    projectScoped: true,
    columns: [
      { prop: 'refundNo', label: '退款单号', inFilter: true },
      { prop: 'projectId', label: '小区名称', type: 'project' },
      { prop: 'orderNo', label: '原订单号', inFilter: true },
      { prop: 'memberName', label: '业主/住户', inFilter: true },
      { prop: 'memberMobile', label: '手机号' },
      { prop: 'houseNo', label: '房号' },
      { prop: 'payChannel', label: '原支付方式', type: 'select', options: payChannelOptions },
      { prop: 'orderAmount', label: '原订单金额' },
      { prop: 'refundAmount', label: '申请退款金额' },
      { prop: 'refundedTransactionAmount', label: '已退流水' },
      { prop: 'status', label: '状态', type: 'select', options: refundStatusOptions, inFilter: true },
      { prop: 'reason', label: '原因' },
      { prop: 'refundedAt', label: '退款时间' },
    ],
    showDetails: true,
    detailFields: [
      { prop: 'refundNo', label: '退款单号' },
      { prop: 'projectId', label: '小区名称', type: 'project' },
      { prop: 'orderNo', label: '原订单号' },
      { prop: 'orderId', label: '原订单ID' },
      { prop: 'transactionId', label: '原支付流水ID' },
      { prop: 'memberName', label: '业主/住户' },
      { prop: 'memberMobile', label: '手机号' },
      { prop: 'houseNo', label: '房号' },
      { prop: 'payChannel', label: '原支付方式', type: 'select', options: payChannelOptions },
      { prop: 'orderAmount', label: '原订单金额' },
      { prop: 'refundAmount', label: '申请退款金额' },
      { prop: 'refundedTransactionAmount', label: '已退流水' },
      { prop: 'status', label: '状态', type: 'select', options: refundStatusOptions },
      { prop: 'thirdRefundNo', label: '第三方/线下退款流水' },
      { prop: 'reason', label: '退款原因' },
      { prop: 'applyUserId', label: '申请人ID' },
      { prop: 'auditUserId', label: '审核人ID' },
      { prop: 'auditAt', label: '审核时间' },
      { prop: 'refundedAt', label: '退款时间' },
      { prop: 'createdAt', label: '创建时间' },
    ],
    fields: [
      { prop: 'projectId', label: '小区名称', type: 'project', required: true },
      { prop: 'orderId', label: '订单ID', type: 'number', required: true },
      { prop: 'refundAmount', label: '本次退款金额', type: 'number', required: true },
      { prop: 'reason', label: '退款原因', type: 'textarea', required: true },
    ],
  },
]

const billingExtraPages: PageConfig[] = [
  {
    key: 'fee-standards',
    title: '收费标准',
    group: '收费账务',
    route: '/fee/standards',
    icon: Coin,
    listPath: '/fee/standards',
    createPath: '/fee/standards',
    updatePath: '/fee/standards/:standardId',
    idProp: 'standardId',
    permission: 'fee:standard:list',
    createPermission: 'fee:standard:create',
    updatePermission: 'fee:standard:update',
    projectScoped: true,
    columns: [
      { prop: 'projectId', label: '小区名称', type: 'project' },
      { prop: 'itemId', label: '收费项目', type: 'feeItem', inFilter: true },
      { prop: 'chargeMethod', label: '计费方式', type: 'select', options: chargeMethodOptions },
      { prop: 'unitPrice', label: '单价' },
      { prop: 'cycle', label: '周期', type: 'select', options: billingCycleOptions },
      { prop: 'effectiveDate', label: '生效日期' },
      { prop: 'expireDate', label: '失效日期' },
      { prop: 'status', label: '状态', type: 'select', options: enabledStatusOptions, inFilter: true },
    ],
    fields: [
      { prop: 'projectId', label: '小区名称', type: 'project', required: true },
      { prop: 'itemId', label: '收费项目', type: 'feeItem', required: true },
      { prop: 'chargeMethod', label: '计费方式', type: 'select', options: chargeMethodOptions, required: true },
      { prop: 'unitPrice', label: '单价', type: 'number', required: true },
      { prop: 'cycle', label: '周期', type: 'select', options: billingCycleOptions },
      { prop: 'formula', label: '公式', type: 'textarea' },
      { prop: 'effectiveDate', label: '生效日期', type: 'date', required: true },
      { prop: 'expireDate', label: '失效日期', type: 'date' },
      { prop: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
    ],
  },
  {
    key: 'fee-standard-binds',
    title: '收费绑定',
    group: '收费账务',
    route: '/fee/standard-binds',
    icon: Tickets,
    listPath: '/fee/standard-binds',
    createPath: '/fee/standard-binds',
    idProp: 'bindId',
    permission: 'fee:standardBind:list',
    createPermission: 'fee:standardBind:create',
    projectScoped: true,
    columns: [
      { prop: 'projectId', label: '小区名称', type: 'project' },
      { prop: 'standardId', label: '收费标准', type: 'feeStandard' },
      { prop: 'objectType', label: '对象类型', type: 'select', options: billObjectTypeOptions, inFilter: true },
      { prop: 'objectId', label: '对象ID' },
      { prop: 'effectiveDate', label: '生效日期' },
      { prop: 'expireDate', label: '失效日期' },
      { prop: 'status', label: '状态', type: 'select', options: enabledStatusOptions, inFilter: true },
    ],
    fields: [
      { prop: 'projectId', label: '小区名称', type: 'project', required: true },
      { prop: 'standardId', label: '收费标准', type: 'feeStandard', required: true },
      { prop: 'objectType', label: '对象类型', type: 'select', options: billObjectTypeOptions },
      { prop: 'objectId', label: '绑定对象', type: 'billObject', required: true },
      { prop: 'effectiveDate', label: '生效日期', type: 'date', required: true },
      { prop: 'expireDate', label: '失效日期', type: 'date' },
      { prop: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
    ],
  },
  {
    key: 'payment-transactions',
    title: '支付流水',
    group: '收费账务',
    route: '/payment/transactions',
    icon: TrendCharts,
    listPath: '/payment/transactions',
    permission: 'payment:transaction:list',
    projectScoped: true,
    showDetails: true,
    columns: [
      { prop: 'transactionId', label: '流水ID', inFilter: true },
      { prop: 'projectId', label: '小区名称', type: 'project' },
      { prop: 'orderNo', label: '订单号', inFilter: true },
      { prop: 'memberName', label: '业主/住户', inFilter: true },
      { prop: 'memberMobile', label: '手机号' },
      { prop: 'thirdTradeNo', label: '第三方流水号' },
      { prop: 'amount', label: '实收金额' },
      { prop: 'payChannel', label: '支付方式', type: 'select', options: payChannelOptions, inFilter: true },
      { prop: 'houseNo', label: '房号' },
      { prop: 'billSummary', label: '应收明细' },
      { prop: 'orderStatus', label: '订单状态', type: 'select', options: payOrderStatusOptions, inFilter: true },
      { prop: 'billAppliedAmount', label: '核销账单金额' },
      { prop: 'prepaymentAmount', label: '转预存款' },
      { prop: 'paidAt', label: '支付时间' },
    ],
    detailFields: [
      { prop: 'transactionId', label: '流水ID' },
      { prop: 'projectId', label: '小区名称', type: 'project' },
      { prop: 'orderNo', label: '订单号' },
      { prop: 'orderId', label: '订单ID' },
      { prop: 'memberName', label: '业主/住户' },
      { prop: 'memberMobile', label: '手机号' },
      { prop: 'memberId', label: '会员ID' },
      { prop: 'houseNo', label: '房号' },
      { prop: 'billSummary', label: '应收明细' },
      { prop: 'thirdTradeNo', label: '第三方流水号' },
      { prop: 'payChannel', label: '支付方式', type: 'select', options: payChannelOptions },
      { prop: 'amount', label: '流水金额' },
      { prop: 'orderAmount', label: '订单金额' },
      { prop: 'billAppliedAmount', label: '核销账单金额' },
      { prop: 'orderStatus', label: '订单状态', type: 'select', options: payOrderStatusOptions },
      { prop: 'prepaymentAmount', label: '转入预存款' },
      { prop: 'paidAt', label: '支付时间' },
      { prop: 'createdAt', label: '创建时间' },
    ],
  },
  {
    key: 'payment-prepayments',
    title: '预存款管理',
    group: '收费账务',
    route: '/payment/prepayments',
    icon: Coin,
    listPath: '/payment/prepayments',
    permission: 'payment:prepayment:list',
    projectScoped: true,
    showDetails: true,
    columns: [
      { prop: 'projectId', label: '小区名称', type: 'project' },
      { prop: 'memberName', label: '业主/住户', inFilter: true },
      { prop: 'mobile', label: '手机号' },
      { prop: 'orderNo', label: '来源订单', inFilter: true },
      { prop: 'amount', label: '预存金额' },
      { prop: 'usedAmount', label: '已抵扣' },
      { prop: 'remainingAmount', label: '可用余额' },
      { prop: 'source', label: '来源', type: 'select', options: prepaymentSourceOptions },
      { prop: 'remark', label: '备注' },
      { prop: 'createdAt', label: '产生时间' },
    ],
  },
  {
    key: 'payment-reconcile',
    title: '支付对账',
    group: '收费账务',
    route: '/payment/reconcile',
    icon: DataAnalysis,
    listPath: '/payment/reconcile',
    permission: 'payment:reconcile:view',
    projectScoped: true,
    columns: [
      { prop: 'projectId', label: '小区名称', type: 'project' },
      { prop: 'startDate', label: '开始日期', type: 'date', inFilter: true, tableHidden: true },
      { prop: 'endDate', label: '结束日期', type: 'date', inFilter: true, tableHidden: true },
      { prop: 'payChannel', label: '支付方式', type: 'select', options: payChannelOptions, inFilter: true, tableHidden: true },
      { prop: 'orderStatus', label: '订单状态', type: 'select', options: payOrderStatusOptions, inFilter: true, tableHidden: true },
      { prop: 'transactionCount', label: '支付流水数' },
      { prop: 'refundCount', label: '退款流水数' },
      { prop: 'orderCount', label: '已收/退款订单数' },
      { prop: 'paidAmount', label: '实收流水金额' },
      { prop: 'refundAmount', label: '退款流水金额' },
      { prop: 'netAmount', label: '净收款' },
      { prop: 'orderPaidAmount', label: '订单应收合计' },
      { prop: 'billAppliedAmount', label: '账单核销金额' },
      { prop: 'prepaymentAmount', label: '预存款产生' },
      { prop: 'prepaymentUsedAmount', label: '预存款抵扣' },
      { prop: 'exceptionAmount', label: '未处理异常金额' },
      { prop: 'exceptionCount', label: '未处理异常数' },
    ],
  },
  {
    key: 'payment-reconcile-exceptions',
    title: '账务异常',
    group: '收费账务',
    route: '/payment/reconcile/exceptions',
    icon: DataAnalysis,
    listPath: '/payment/reconcile/exceptions',
    permission: 'payment:reconcile:view',
    projectScoped: true,
    showDetails: true,
    columns: [
      { prop: 'projectId', label: '小区名称', type: 'project' },
      { prop: 'exceptionType', label: '异常类型', type: 'select', options: reconcileExceptionTypeOptions, inFilter: true },
      { prop: 'exceptionLevel', label: '级别' },
      { prop: 'businessType', label: '业务类型' },
      { prop: 'businessNo', label: '业务单号', inFilter: true },
      { prop: 'memberName', label: '业主/住户', inFilter: true },
      { prop: 'memberMobile', label: '手机号' },
      { prop: 'amount', label: '差异金额' },
      { prop: 'reason', label: '异常原因' },
      { prop: 'status', label: '处理状态', type: 'select', options: reconcileExceptionStatusOptions, inFilter: true },
      { prop: 'handledAt', label: '处理时间' },
      { prop: 'handleRemark', label: '处理备注' },
      { prop: 'createdAt', label: '发现时间' },
    ],
    detailFields: [
      { prop: 'projectId', label: '小区名称', type: 'project' },
      { prop: 'exceptionType', label: '异常类型' },
      { prop: 'exceptionLevel', label: '级别' },
      { prop: 'businessType', label: '业务类型' },
      { prop: 'businessId', label: '业务ID' },
      { prop: 'businessNo', label: '业务单号' },
      { prop: 'memberName', label: '业主/住户' },
      { prop: 'memberMobile', label: '手机号' },
      { prop: 'amount', label: '差异金额' },
      { prop: 'reason', label: '异常原因' },
      { prop: 'status', label: '处理状态', type: 'select', options: reconcileExceptionStatusOptions },
      { prop: 'handledAt', label: '处理时间' },
      { prop: 'handledBy', label: '处理人ID' },
      { prop: 'handleRemark', label: '处理备注' },
      { prop: 'createdAt', label: '发现时间' },
    ],
  },
]

const servicePages: PageConfig[] = [
  {
    key: 'notices',
    title: '公告通知',
    group: '物业服务',
    route: '/service/notices',
    icon: Bell,
    listPath: '/service/notices',
    createPath: '/service/notices',
    idProp: 'noticeId',
    permission: 'service:notice:list',
    createPermission: 'service:notice:create',
    projectScoped: true,
    columns: [
      { prop: 'title', label: '标题', inFilter: true },
      { prop: 'noticeType', label: '类型' },
      { prop: 'targetScope', label: '范围' },
      { prop: 'publishStatus', label: '状态' },
      { prop: 'publishedAt', label: '发布时间' },
    ],
    fields: [
      { prop: 'projectId', label: '项目ID', type: 'number' },
      { prop: 'title', label: '标题', required: true },
      { prop: 'content', label: '内容', type: 'textarea', required: true },
      { prop: 'noticeType', label: '类型', type: 'select', options: ['PROPERTY', 'SYSTEM', 'ACTIVITY', 'BILL'] },
      { prop: 'targetScope', label: '范围', type: 'select', options: ['TENANT', 'PROJECT', 'MEMBER', 'HOUSE'] },
    ],
  },
  {
    key: 'workorders',
    title: '工单管理',
    group: '物业服务',
    route: '/service/workorders',
    icon: Tools,
    listPath: '/service/workorders',
    createPath: '/service/workorders',
    idProp: 'workOrderId',
    permission: 'service:workorder:list',
    createPermission: 'service:workorder:create',
    projectScoped: true,
    columns: [
      { prop: 'orderNo', label: '工单号', inFilter: true },
      { prop: 'orderType', label: '类型' },
      { prop: 'title', label: '标题' },
      { prop: 'priority', label: '优先级' },
      { prop: 'status', label: '状态', inFilter: true },
    ],
    fields: [
      { prop: 'projectId', label: '项目ID', type: 'number', required: true },
      { prop: 'orderType', label: '类型', type: 'select', options: ['REPAIR', 'COMPLAINT', 'SUGGESTION', 'HOUSEKEEPING', 'RENOVATION'] },
      { prop: 'title', label: '标题', required: true },
      { prop: 'description', label: '描述', type: 'textarea' },
      { prop: 'priority', label: '优先级', type: 'select', options: ['LOW', 'NORMAL', 'HIGH', 'URGENT'] },
    ],
  },
  {
    key: 'complaints',
    title: '投诉建议',
    group: '物业服务',
    route: '/service/complaints',
    icon: Tools,
    listPath: '/service/complaints',
    idProp: 'workOrderId',
    permission: 'service:complaint:list',
    projectScoped: true,
    columns: [
      { prop: 'orderNo', label: '单号', inFilter: true },
      { prop: 'orderType', label: '类型', inFilter: true },
      { prop: 'title', label: '标题' },
      { prop: 'memberId', label: '会员ID' },
      { prop: 'status', label: '状态', inFilter: true },
      { prop: 'createdAt', label: '提交时间' },
    ],
  },
  {
    key: 'service-messages',
    title: '消息记录',
    group: '物业服务',
    route: '/service/messages',
    icon: Bell,
    listPath: '/service/messages',
    permission: 'service:message:list',
    projectScoped: true,
    columns: [
      { prop: 'title', label: '标题', inFilter: true },
      { prop: 'channel', label: '渠道', inFilter: true },
      { prop: 'receiverType', label: '接收方' },
      { prop: 'receiverId', label: '接收ID' },
      { prop: 'sendStatus', label: '状态', inFilter: true },
      { prop: 'failReason', label: '失败原因' },
      { prop: 'createdAt', label: '创建时间' },
    ],
  },
  {
    key: 'message-templates',
    title: '消息模板',
    group: '物业服务',
    route: '/service/message-templates',
    icon: Tickets,
    listPath: '/service/message-templates',
    createPath: '/service/message-templates',
    updatePath: '/service/message-templates/:templateId',
    idProp: 'templateId',
    permission: 'service:messageTemplate:list',
    createPermission: 'service:messageTemplate:create',
    updatePermission: 'service:messageTemplate:update',
    columns: [
      { prop: 'templateCode', label: '模板编码', inFilter: true },
      { prop: 'templateName', label: '模板名称', inFilter: true },
      { prop: 'channel', label: '渠道', inFilter: true },
      { prop: 'status', label: '状态', inFilter: true },
      { prop: 'createdAt', label: '创建时间' },
    ],
    fields: [
      { prop: 'templateCode', label: '模板编码', required: true },
      { prop: 'templateName', label: '模板名称', required: true },
      { prop: 'channel', label: '渠道', type: 'select', options: ['SITE', 'SMS', 'WECHAT'], required: true },
      { prop: 'titleTemplate', label: '标题模板', required: true },
      { prop: 'contentTemplate', label: '内容模板', type: 'textarea', required: true },
      { prop: 'status', label: '状态', type: 'select', options: ['ACTIVE', 'DISABLED'] },
    ],
  },
]

const systemPages: PageConfig[] = [
  {
    key: 'system-depts',
    title: '部门管理',
    group: '系统设置',
    route: '/system/depts',
    icon: OfficeBuilding,
    listPath: '/system/depts',
    createPath: '/system/depts',
    updatePath: '/system/depts/:deptId',
    idProp: 'deptId',
    permission: 'system:dept:list',
    createPermission: 'system:dept:create',
    updatePermission: 'system:dept:update',
    columns: [
      { prop: 'deptName', label: '部门名称', inFilter: true },
      { prop: 'parentId', label: '上级ID' },
      { prop: 'sortOrder', label: '排序' },
      { prop: 'status', label: '状态', inFilter: true },
    ],
    fields: [
      { prop: 'deptName', label: '部门名称', required: true },
      { prop: 'parentId', label: '上级ID', type: 'number' },
      { prop: 'sortOrder', label: '排序', type: 'number' },
      { prop: 'status', label: '状态', type: 'select', options: ['ACTIVE', 'DISABLED'] },
    ],
  },
  {
    key: 'system-users',
    title: '用户管理',
    group: '系统设置',
    route: '/system/users',
    icon: User,
    listPath: '/system/users',
    createPath: '/system/users',
    updatePath: '/system/users/:userId',
    idProp: 'userId',
    permission: 'system:user:list',
    createPermission: 'system:user:create',
    updatePermission: 'system:user:update',
    columns: [
      { prop: 'username', label: '用户名', inFilter: true },
      { prop: 'realName', label: '姓名' },
      { prop: 'mobile', label: '手机号' },
      { prop: 'userType', label: '类型' },
      { prop: 'status', label: '状态', inFilter: true },
    ],
    fields: [
      { prop: 'username', label: '用户名', required: true },
      { prop: 'realName', label: '姓名', required: true },
      { prop: 'mobile', label: '手机号' },
      { prop: 'deptId', label: '部门ID', type: 'number' },
      { prop: 'roleId', label: '角色ID', type: 'number' },
      { prop: 'status', label: '状态', type: 'select', options: ['ACTIVE', 'DISABLED'] },
    ],
  },
  {
    key: 'system-roles',
    title: '角色管理',
    group: '系统设置',
    route: '/system/roles',
    icon: Setting,
    listPath: '/system/roles',
    createPath: '/system/roles',
    updatePath: '/system/roles/:roleId',
    idProp: 'roleId',
    permission: 'system:role:list',
    createPermission: 'system:role:create',
    updatePermission: 'system:role:update',
    columns: [
      { prop: 'roleName', label: '角色名称', inFilter: true },
      { prop: 'roleCode', label: '角色编码' },
      { prop: 'dataScope', label: '数据范围' },
      { prop: 'status', label: '状态', inFilter: true },
    ],
    fields: [
      { prop: 'roleName', label: '角色名称', required: true },
      { prop: 'roleCode', label: '角色编码', required: true },
      { prop: 'dataScope', label: '数据范围', type: 'select', options: ['ALL', 'PROJECT', 'SELF'] },
      { prop: 'status', label: '状态', type: 'select', options: ['ACTIVE', 'DISABLED'] },
    ],
  },
  {
    key: 'system-menus',
    title: '菜单权限',
    group: '系统设置',
    route: '/system/menus',
    icon: Key,
    listPath: '/system/menus',
    permission: 'system:menu:list',
    columns: [
      { prop: 'menuName', label: '菜单名称', inFilter: true },
      { prop: 'permissionCode', label: '权限码' },
      { prop: 'moduleCode', label: '模块' },
      { prop: 'apiPath', label: '接口路径' },
      { prop: 'status', label: '状态' },
    ],
  },
]

const operationPages: PageConfig[] = [
  {
    key: 'patrol-assets',
    title: '巡检资产',
    group: '巡检租赁设备',
    route: '/patrol/assets',
    icon: Tools,
    listPath: '/patrol/assets',
    createPath: '/patrol/assets',
    idProp: 'equipmentId',
    permission: 'patrol:asset:list',
    createPermission: 'patrol:asset:create',
    projectScoped: true,
    columns: [
      { prop: 'equipmentName', label: '资产名称', inFilter: true },
      { prop: 'equipmentCode', label: '资产编码' },
      { prop: 'equipmentType', label: '类型' },
      { prop: 'status', label: '状态', inFilter: true },
    ],
    fields: [
      { prop: 'projectId', label: '项目ID', type: 'number', required: true },
      { prop: 'equipmentName', label: '资产名称', required: true },
      { prop: 'equipmentCode', label: '资产编码', required: true },
      { prop: 'equipmentType', label: '类型' },
      { prop: 'location', label: '位置' },
      { prop: 'status', label: '状态', type: 'select', options: ['ACTIVE', 'DISABLED'] },
    ],
  },
  {
    key: 'patrol-points',
    title: '巡检点位',
    group: '巡检租赁设备',
    route: '/patrol/points',
    icon: Key,
    listPath: '/patrol/points',
    createPath: '/patrol/points',
    idProp: 'pointId',
    permission: 'patrol:point:list',
    createPermission: 'patrol:point:create',
    projectScoped: true,
    columns: [
      { prop: 'pointName', label: '点位名称', inFilter: true },
      { prop: 'pointCode', label: '点位编码' },
      { prop: 'equipmentId', label: '资产ID' },
      { prop: 'status', label: '状态', inFilter: true },
    ],
    fields: [
      { prop: 'projectId', label: '项目ID', type: 'number', required: true },
      { prop: 'equipmentId', label: '资产ID', type: 'number' },
      { prop: 'pointName', label: '点位名称', required: true },
      { prop: 'pointCode', label: '点位编码', required: true },
      { prop: 'location', label: '位置' },
      { prop: 'status', label: '状态', type: 'select', options: ['ACTIVE', 'DISABLED'] },
    ],
  },
  {
    key: 'patrol-plans',
    title: '巡检计划',
    group: '巡检租赁设备',
    route: '/patrol/plans',
    icon: Tickets,
    listPath: '/patrol/plans',
    createPath: '/patrol/plans',
    idProp: 'planId',
    permission: 'patrol:plan:list',
    createPermission: 'patrol:plan:create',
    projectScoped: true,
    columns: [
      { prop: 'planName', label: '计划名称', inFilter: true },
      { prop: 'cycleType', label: '周期' },
      { prop: 'executorUserId', label: '执行人ID' },
      { prop: 'status', label: '状态', inFilter: true },
    ],
    fields: [
      { prop: 'projectId', label: '项目ID', type: 'number', required: true },
      { prop: 'planName', label: '计划名称', required: true },
      { prop: 'cycleType', label: '周期', type: 'select', options: ['DAY', 'WEEK', 'MONTH'] },
      { prop: 'executorUserId', label: '执行人ID', type: 'number' },
      { prop: 'status', label: '状态', type: 'select', options: ['ACTIVE', 'DISABLED'] },
    ],
  },
  {
    key: 'patrol-tasks',
    title: '巡检任务',
    group: '巡检租赁设备',
    route: '/patrol/tasks',
    icon: Key,
    listPath: '/patrol/tasks',
    createPath: '/patrol/tasks',
    idProp: 'taskId',
    permission: 'patrol:task:list',
    createPermission: 'patrol:task:create',
    projectScoped: true,
    columns: [
      { prop: 'taskNo', label: '任务号', inFilter: true },
      { prop: 'taskName', label: '任务名称' },
      { prop: 'plannedStartAt', label: '计划开始' },
      { prop: 'status', label: '状态' },
    ],
    fields: [
      { prop: 'projectId', label: '项目ID', type: 'number', required: true },
      { prop: 'taskName', label: '任务名称', required: true },
      { prop: 'plannedStartAt', label: '计划开始', type: 'datetime', required: true },
      { prop: 'plannedEndAt', label: '计划结束', type: 'datetime', required: true },
    ],
  },
  {
    key: 'lease-resources',
    title: '可租资源',
    group: '巡检租赁设备',
    route: '/lease/resources',
    icon: OfficeBuilding,
    listPath: '/lease/resources',
    createPath: '/lease/resources',
    idProp: 'resourceId',
    permission: 'lease:resource:list',
    createPermission: 'lease:resource:create',
    projectScoped: true,
    columns: [
      { prop: 'resourceName', label: '资源名称', inFilter: true },
      { prop: 'resourceType', label: '类型' },
      { prop: 'area', label: '面积' },
      { prop: 'rentAmount', label: '租金' },
      { prop: 'status', label: '状态', inFilter: true },
    ],
    fields: [
      { prop: 'projectId', label: '项目ID', type: 'number', required: true },
      { prop: 'resourceName', label: '资源名称', required: true },
      { prop: 'resourceType', label: '类型', type: 'select', options: ['SHOP', 'OFFICE', 'PARKING', 'AD_SPACE'] },
      { prop: 'area', label: '面积', type: 'number' },
      { prop: 'rentAmount', label: '租金', type: 'number' },
      { prop: 'status', label: '状态', type: 'select', options: ['AVAILABLE', 'RENTED', 'DISABLED'] },
    ],
  },
  {
    key: 'lease-customers',
    title: '意向客户',
    group: '巡检租赁设备',
    route: '/lease/customers',
    icon: User,
    listPath: '/lease/customers',
    createPath: '/lease/customers',
    idProp: 'customerId',
    permission: 'lease:customer:list',
    createPermission: 'lease:customer:create',
    projectScoped: true,
    columns: [
      { prop: 'customerName', label: '客户姓名', inFilter: true },
      { prop: 'mobile', label: '手机号' },
      { prop: 'intentionType', label: '意向类型' },
      { prop: 'status', label: '状态', inFilter: true },
    ],
    fields: [
      { prop: 'projectId', label: '项目ID', type: 'number', required: true },
      { prop: 'customerName', label: '客户姓名', required: true },
      { prop: 'mobile', label: '手机号' },
      { prop: 'intentionType', label: '意向类型' },
      { prop: 'remark', label: '备注', type: 'textarea' },
      { prop: 'status', label: '状态', type: 'select', options: ['FOLLOWING', 'SIGNED', 'LOST'] },
    ],
  },
  {
    key: 'lease-contracts',
    title: '租赁合同',
    group: '巡检租赁设备',
    route: '/lease/contracts',
    icon: Files,
    listPath: '/lease/contracts',
    createPath: '/lease/contracts',
    idProp: 'contractId',
    permission: 'lease:contract:list',
    createPermission: 'lease:contract:create',
    projectScoped: true,
    columns: [
      { prop: 'contractNo', label: '合同号', inFilter: true },
      { prop: 'lesseeName', label: '承租人' },
      { prop: 'rentAmount', label: '租金' },
      { prop: 'endDate', label: '到期日' },
      { prop: 'status', label: '状态' },
    ],
    fields: [
      { prop: 'projectId', label: '项目ID', type: 'number', required: true },
      { prop: 'resourceId', label: '资源ID', type: 'number', required: true },
      { prop: 'lesseeName', label: '承租人', required: true },
      { prop: 'startDate', label: '开始日期', type: 'date', required: true },
      { prop: 'endDate', label: '结束日期', type: 'date', required: true },
      { prop: 'rentAmount', label: '租金', type: 'number', required: true },
      { prop: 'depositAmount', label: '押金', type: 'number' },
    ],
  },
  {
    key: 'device-configs',
    title: '设备配置',
    group: '巡检租赁设备',
    route: '/device/configs',
    icon: Setting,
    listPath: '/device/configs',
    createPath: '/device/configs',
    updatePath: '/device/configs/:deviceId',
    idProp: 'deviceId',
    permission: 'device:config:list',
    createPermission: 'device:config:create',
    updatePermission: 'device:config:update',
    projectScoped: true,
    columns: [
      { prop: 'deviceName', label: '设备名称', inFilter: true },
      { prop: 'deviceType', label: '类型' },
      { prop: 'vendorCode', label: '厂商' },
      { prop: 'status', label: '状态', inFilter: true },
    ],
    fields: [
      { prop: 'projectId', label: '项目ID', type: 'number', required: true },
      { prop: 'deviceName', label: '设备名称', required: true },
      { prop: 'deviceCode', label: '设备编码', required: true },
      { prop: 'deviceType', label: '设备类型', type: 'select', options: ['ACCESS', 'PARKING', 'CAMERA', 'ELEVATOR'] },
      { prop: 'vendorCode', label: '厂商编码' },
      { prop: 'status', label: '状态', type: 'select', options: ['ACTIVE', 'DISABLED'] },
    ],
  },
  {
    key: 'device-visitors',
    title: '访客管理',
    group: '巡检租赁设备',
    route: '/device/visitors',
    icon: User,
    listPath: '/device/visitors',
    createPath: '/device/visitors',
    idProp: 'visitorId',
    permission: 'device:visitor:list',
    createPermission: 'device:visitor:create',
    projectScoped: true,
    columns: [
      { prop: 'visitorName', label: '访客', inFilter: true },
      { prop: 'visitorMobile', label: '手机' },
      { prop: 'validStartAt', label: '开始' },
      { prop: 'validEndAt', label: '结束' },
      { prop: 'status', label: '状态' },
    ],
    fields: [
      { prop: 'projectId', label: '项目ID', type: 'number', required: true },
      { prop: 'visitorName', label: '访客姓名', required: true },
      { prop: 'visitorMobile', label: '手机号' },
      { prop: 'visitReason', label: '来访事由' },
      { prop: 'validStartAt', label: '有效开始', type: 'datetime', required: true },
      { prop: 'validEndAt', label: '有效结束', type: 'datetime', required: true },
    ],
  },
  {
    key: 'device-access',
    title: '门禁权限',
    group: '巡检租赁设备',
    route: '/device/access',
    icon: Key,
    listPath: '/device/access',
    createPath: '/device/access',
    idProp: 'permissionId',
    permission: 'device:access:list',
    createPermission: 'device:access:create',
    projectScoped: true,
    columns: [
      { prop: 'deviceId', label: '设备ID' },
      { prop: 'memberId', label: '成员ID' },
      { prop: 'status', label: '状态', inFilter: true },
      { prop: 'syncStatus', label: '同步状态', inFilter: true },
    ],
    fields: [
      { prop: 'projectId', label: '项目ID', type: 'number', required: true },
      { prop: 'deviceId', label: '设备ID', type: 'number', required: true },
      { prop: 'memberId', label: '成员ID', type: 'number', required: true },
      { prop: 'validStartAt', label: '有效开始', type: 'datetime' },
      { prop: 'validEndAt', label: '有效结束', type: 'datetime' },
    ],
  },
  {
    key: 'device-access-records',
    title: '门禁记录',
    group: '巡检租赁设备',
    route: '/device/access/records',
    icon: Files,
    listPath: '/device/access/records',
    createPath: '/device/access/records',
    idProp: 'recordId',
    permission: 'device:access:record:list',
    createPermission: 'device:access:record:create',
    projectScoped: true,
    columns: [
      { prop: 'deviceId', label: '设备ID' },
      { prop: 'personName', label: '人员姓名', inFilter: true },
      { prop: 'accessType', label: '通行类型' },
      { prop: 'accessTime', label: '通行时间' },
    ],
    fields: [
      { prop: 'projectId', label: '项目ID', type: 'number', required: true },
      { prop: 'deviceId', label: '设备ID', type: 'number', required: true },
      { prop: 'personName', label: '人员姓名', required: true },
      { prop: 'accessType', label: '通行类型', type: 'select', options: ['IN', 'OUT'] },
      { prop: 'accessTime', label: '通行时间', type: 'datetime', required: true },
    ],
  },
  {
    key: 'device-parking',
    title: '停车对接',
    group: '巡检租赁设备',
    route: '/device/parking',
    icon: Van,
    listPath: '/device/parking',
    permission: 'device:parking:list',
    projectScoped: true,
    columns: [
      { prop: 'vendorCode', label: '厂商' },
      { prop: 'plateNo', label: '车牌', inFilter: true },
      { prop: 'syncType', label: '同步类型' },
      { prop: 'syncStatus', label: '状态', inFilter: true },
      { prop: 'retryCount', label: '重试次数' },
    ],
  },
  {
    key: 'import-batches',
    title: '导入批次',
    group: '运维工具',
    route: '/import/batches',
    icon: Files,
    listPath: '/import/batches',
    idProp: 'batchId',
    permission: 'import:batch:list',
    projectScoped: true,
    columns: [
      { prop: 'batchNo', label: '批次号', inFilter: true },
      { prop: 'importType', label: '导入类型', inFilter: true },
      { prop: 'importStatus', label: '状态', inFilter: true },
      { prop: 'totalCount', label: '总数' },
      { prop: 'successCount', label: '成功' },
      { prop: 'failCount', label: '失败' },
      { prop: 'createdAt', label: '创建时间' },
    ],
  },
  {
    key: 'file-objects',
    title: '文件对象',
    group: '运维工具',
    route: '/files',
    icon: Files,
    listPath: '/files',
    idProp: 'fileId',
    permission: 'file:object:list',
    projectScoped: true,
    columns: [
      { prop: 'fileId', label: '文件ID', inFilter: true },
      { prop: 'moduleCode', label: '模块', inFilter: true },
      { prop: 'originalName', label: '原始文件名' },
      { prop: 'contentType', label: '类型' },
      { prop: 'fileSize', label: '大小' },
      { prop: 'uploaderType', label: '上传方' },
      { prop: 'createdAt', label: '上传时间' },
    ],
  },
]

export const allPages = [
  ...pages,
  ...baseArchiveExtraPages,
  ...platformExtraPages,
  ...billingPages,
  ...billingExtraPages,
  ...servicePages,
  ...systemPages,
  ...operationPages,
]

export const reportLinks = [
  { label: '报表中心', route: '/reports', permission: 'report:center:view', icon: DataAnalysis },
  { label: '平台运营报表', route: '/report/platform', permission: 'report:platform:view', icon: TrendCharts },
  { label: '运维监控', route: '/platform/monitor', permission: 'platform:monitor:view', icon: Tools },
  { label: '租户配置', route: '/platform/tenant-config', permission: 'platform:tenant:config:view', icon: Setting },
  { label: '任务中心', route: '/jobs', permission: 'job:run', icon: Tools },
]
